repos:
  # Базовые проверки.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml

  # ISORT (сортировка импортов).
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=120"]

  # FLAKE8 (разрешаем camelCase и 120 символов).
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,W503,N802,N803,N806,E111,E114,E231,E302,E305,E501,F401,F841"]

  # MYPY (проверка типов).
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic"
          - "redis"
          - "types-redis"
        args: ["--ignore-missing-imports"]
